version: "2"
services:
  mongo:
    image: mongo
    expose:
     - "27017"
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles
  nanapp:
    container_name: nanapp
    restart: always
    build: .
    environment:
      - DB_CONNECTION_STRING=mongodb://mongo:27017
    ports:
      - "8080:8080"
    links:
      - mongo:mongo
    depends_on:
      - mongo